source 'https://rubygems.org'
gem 'sinatra', :require => 'sinatra/base'
gem 'sinatra-reloader'
gem 'json'
gem 'rest-client'
gem 'haml'
gem 'rack'
gem 'data_mapper'
gem 'dm-postgres-adapter'
gem 'rake'
gem 'yard'