require_relative 'players'
require_relative 'passing_stats'
require_relative 'rushing_stats'
require_relative 'sack_stats'
require_relative 'fumble_stats'
require_relative 'receiving_stats'
require_relative 'kickoff_return_stats'
require_relative 'punt_return_stats'
